name: PathogenTrack
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - samtools=1.9
  - star>2.5
  - fastp
  - python>3.6
  - biopython
  - umi_tools=1.1.1
  - kraken2=2.1.1
  - pip
  - pip:
    - pathogentrack

